name: Build and Publish

on:
  push:

permissions:
  packages: write
  contents: read

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - hanprom
          - gpsprom
          - upsprom
          - ocppprom

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Build binaries
        run: |
          make ${{ matrix.package }}

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: cmd/${{ matrix.package }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/calmh/${{ matrix.package }}:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
