name: Build and Publish

on:
  push:

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Setup ko
        uses: ko-build/setup-ko@v0.6

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build kontainers
        run: |
          git fetch --tags
          descr=$(git describe --tags)
          short=$(git describe --tags --abbrev=0)
          export version="${descr#v}"
          if [[ $descr == $short ]]; then
            minor="${version%.*}"
            major="${version%%.*}"
            tags=(-t edge -t latest -t "$version" -t "$minor" -t "$major")
          else
            tags=(-t edge)
          fi
          ko build --base-import-paths --sbom=none "${tags[@]}" ./cmd/*prom
        env:
          KO_DOCKER_REPO: ghcr.io/calmh
